site_name: DoCCoD
theme:
  name: material
  font:
    text: Roboto Mono
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  palette: 
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
extra:
  analytics: 
    provider: google
    property: UA-XXXXXXXX-X
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
    # social:
    #   - icon: fontawesome/brands/twitter 
    #     link: https://twitter.com/squidfunk
  #   consent:
  #     title: Cookie consent
  #     description: >- 
  #       We use cookies to recognize your repeated visits and preferences, as well
  #       as to measure the effectiveness of our documentation and whether users
  #       find what they're searching for. With your consent, you're helping us to
  #       make our documentation better.
  #     cookies:
  #       analytics: Custom name
  #     actions:
  #       - accept
  #       - manage 
markdown_extensions: 
  - attr_list
  - md_in_html 
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
  - glightbox
nav: 
  - Home: index.md
  - Linux:
      Network: 
        - linux/network/arp.md
        - linux/network/curl.md
        - linux/network/netplan.md
      Storage:
        - linux/storage/lvm.md

