name: Mdbook build

on:
  push:
    branches: ["mdbook"]

jobs:
  build:
    name: build
    runs-on: rust:1.82.0
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install mdbook
      run: |
        cargo install mdbook mdbook-pagecrypt
    - name: Build
      run: mdbook build
    # share between different jobs
    - uses: actions/upload-artifact@v4
      with:
        name: book
        path: book/