name: Mdbook build

on:
  push:
    branches: ["mdbook"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: cargo install mdbook mdbook-pagecrypt

    - name: Build
      run: mdbook build

    - uses: actions/upload-artifact@v4
      with:
        name: book
        path: book/